apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: habit-tracker-service
  labels:
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      containers:
        - image: asia-northeast1-docker.pkg.dev/PROJECT_ID/habit-tracker-repo/habit-tracker:latest
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          volumeMounts:
            - name: db-volume
              mountPath: /app/data
      volumes:
        - name: db-volume
          csi:
            driver: gcsfuse.run.googleapis.net
            volumeAttributes:
              bucketName: PROJECT_ID-db-bucket
